# Generated by Django 4.0.6 on 2023-01-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_alter_comment_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
